name: Split PHP Subtree

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  split-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Monorepo Split of PHP Package
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: 'packages/php'
          repository_organization: 'Codaminds'
          repository_name: 'identifiers-php'
          user_name: 'codediaz'
          user_email: 'codediaz@outlook.es'
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}